// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3WjAV7XatPEmzSmdqdIxTSQCd__yVaY',
    appId: '1:311316864375:web:32e132d9e049c99303d572',
    messagingSenderId: '311316864375',
    projectId: 'spacelab-2dd51',
    authDomain: 'spacelab-2dd51.firebaseapp.com',
    storageBucket: 'spacelab-2dd51.appspot.com',
    measurementId: 'G-2WVSX1ZNP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9c0WUdiDa_9UCAH5rgP0yWAEuBd5gKnk',
    appId: '1:311316864375:android:3c395c7e8384f2c803d572',
    messagingSenderId: '311316864375',
    projectId: 'spacelab-2dd51',
    storageBucket: 'spacelab-2dd51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWIoocbKZ1Ut6bI3j0VgkiRLGW654PliI',
    appId: '1:311316864375:ios:4732fff1a7e5068203d572',
    messagingSenderId: '311316864375',
    projectId: 'spacelab-2dd51',
    storageBucket: 'spacelab-2dd51.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWIoocbKZ1Ut6bI3j0VgkiRLGW654PliI',
    appId: '1:311316864375:ios:cef36c1997ed206503d572',
    messagingSenderId: '311316864375',
    projectId: 'spacelab-2dd51',
    storageBucket: 'spacelab-2dd51.appspot.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
